version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: magicfridge
    environment:
      POSTGRES_DB: magicfridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always